<a href="https://colab.research.google.com/github/xpewa/Technopark_ML/blob/main/ML_%D0%94%D0%971.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Задание 1. 
Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.




In [ ]:
import numpy as np
x = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])

In [ ]:
def func_not_vectorize(x):
    res = np.int64(1)
    for i in range(min(np.shape(x))):
        if x[i, i] != 0:
            res *= x[i, i]
    return res
func_not_vectorize(x)

3

In [ ]:
def func_vectorize(x):
    return np.diag(x)[np.diag(x)!=0].prod()
func_vectorize(x)

3

In [ ]:
def func_other(x):
    mas = np.array([])
    for i in np.diag(x):
        if i != 0:
            mas = np.append(mas, i)
    return mas.prod()
func_other(x)

3.0

In [ ]:
x1 = np.random.rand(10, 10)*10
x2 = np.random.rand(100, 100)*10
x3 = np.random.rand(500, 1000)*10

In [ ]:
%timeit func_vectorize(x1)
%timeit func_not_vectorize(x1)
%timeit func_other(x1)

The slowest run took 21.60 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 5: 12.4 µs per loop
The slowest run took 4.16 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 5: 12.5 µs per loop
10000 loops, best of 5: 83.6 µs per loop


In [ ]:
%timeit func_vectorize(x2)
%timeit func_not_vectorize(x2)
%timeit func_other(x2)

The slowest run took 9.23 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 5: 12.9 µs per loop
10000 loops, best of 5: 82 µs per loop
1000 loops, best of 5: 756 µs per loop


In [ ]:
%timeit func_vectorize(x3)
%timeit func_not_vectorize(x3)
%timeit func_other(x3)

The slowest run took 14.94 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 5: 15.6 µs per loop
1000 loops, best of 5: 396 µs per loop
100 loops, best of 5: 3.68 ms per loop


# Задание 2.
Дана матрица X и два вектора одинаковой длины i и j. Построить вектор np.array([X[i[0], j[0]], X[i[1], j[1]], ... , X[i[N-1], j[N-1]]]).

In [ ]:
import numpy as np
X = np.array([[1, 0], [2, 0], [3, 0], [4, 4]])
i = np.array([1, 1])
j = np.array([0, 1])

In [ ]:
def func_not_vectorize(X, i, j):
    res = np.array([])
    for k in range(len(i)):
        res = np.append(res, X[i[k], j[k]])
    return res
func_not_vectorize(X, i, j)

array([2., 0.])

In [ ]:
def func_vectorize(X, i, j):
    return X[i, j]
func_vectorize(X, i, j)

array([2, 0])

In [ ]:
def func_other(X, i ,j):
    mask = np.array(X)
    for k1 in range(X.shape[0]):
        for k2 in range(X.shape[1]):
            if (k1 in i and k2 in j):
                mask[k1, k2] = True
            else:
                mask[k1, k2] = False
    return X[mask != 0]
func_other(X, i, j)

array([2, 0])

In [ ]:
X1 = np.random.rand(50, 50)*10
i1, j1 = (np.random.randint(50, size=10),
          np.random.randint(50, size=10))
X2 = np.random.rand(600, 500)*10
i2, j2 = (np.random.randint(600, size=300),
          np.random.randint(500, size=300))
X3 = np.random.rand(1000, 1000)*10
i3, j3 = (np.random.randint(1000, size=200),
          np.random.randint(1000, size=200))

In [ ]:
%timeit func_vectorize(X1, i1, j1)
%timeit func_not_vectorize(X1, i1, j1)
%timeit func_other(X1, i1, j1)

The slowest run took 1820.87 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 5: 1.28 µs per loop
10000 loops, best of 5: 78.5 µs per loop
100 loops, best of 5: 10.7 ms per loop


In [ ]:
%timeit func_vectorize(X2, i2, j2)
%timeit func_not_vectorize(X2, i2, j2)
%timeit func_other(X2, i2, j2)

The slowest run took 15.72 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 5: 3.43 µs per loop
100 loops, best of 5: 2.2 ms per loop
1 loop, best of 5: 1.52 s per loop


In [ ]:
%timeit func_vectorize(X3, i3, j3)
%timeit func_not_vectorize(X3, i3, j3)
%timeit func_other(X3, i3, j3)

The slowest run took 14.97 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 5: 2.67 µs per loop
1000 loops, best of 5: 1.52 ms per loop
1 loop, best of 5: 4.3 s per loop


# Задание 3.
Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.

In [ ]:
import numpy as np
x = np.array([1, 2, 2, 4])
y = np.array([4, 2, 1, 2])

In [ ]:
def func_not_vectorize(x, y):
    sort_x = sorted(list(x))
    sort_y = sorted(list(y))
    return sort_x == sort_y
func_not_vectorize(x, y)

True

In [ ]:
def func_vectorize(x, y):
    if (x.size != y.size):
        return False
    sort_x = np.sort(x)
    sort_y = np.sort(y)
    return (sort_x == sort_y).all()
func_vectorize(x, y)

True

In [ ]:
def func_other(x, y):
    if (x.size != y.size):
        return False
    sort_x = sorted(list(x))
    sort_y = sorted(list(y))
    for i in range(len(x)):
        if sort_x[i] != sort_y[i]:
            return False
    return True
func_other(x, y)

True

In [ ]:
x1 = np.random.rand(50)*10
y1 = x1[::-1]
x2 = np.random.rand(1000)*10
y2 = np.random.rand(1000)*10
x3 = np.random.rand(5000)*10
y3 = x1[::-1]

In [ ]:
%timeit func_vectorize(x1, y1)
%timeit func_not_vectorize(x1, y1)
%timeit func_other(x1, y1)

The slowest run took 406.00 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 5: 9.84 µs per loop
10000 loops, best of 5: 22.7 µs per loop
10000 loops, best of 5: 26.8 µs per loop


In [ ]:
%timeit func_vectorize(x2, y2)
%timeit func_not_vectorize(x2, y2)
%timeit func_other(x, y2)

10000 loops, best of 5: 105 µs per loop
1000 loops, best of 5: 654 µs per loop
The slowest run took 16.08 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 5: 216 ns per loop


In [ ]:
%timeit func_vectorize(x3, y3)
%timeit func_not_vectorize(x3, y3)
%timeit func_other(x3, y3)

The slowest run took 20.67 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 5: 236 ns per loop
1000 loops, best of 5: 1.96 ms per loop
The slowest run took 15.59 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 5: 236 ns per loop


# Задание 4.
Найти максимальный элемент в векторе x среди элементов, перед которыми стоит нулевой.

In [ ]:
import numpy as np
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])

In [ ]:
def func_not_vectorize(x):
    i = 1
    while x[i-1] != 0:
        i = i + 1
    max = x[i]
    for i in range(1, len(x)):
        if (x[i-1] == 0 and x[i] > max):
            max = x[i]
    return max
func_not_vectorize(x)

5

In [ ]:
def func_vectorize(x):
    return np.max(x[1:][x[:-1] == 0])
func_vectorize(x)

5

In [ ]:
def func_other(x):
    mas = np.array([])
    for i in range(1, len(x)):
        if x[i-1] == 0:
            mas = np.append(mas, x[i])
    return np.max(mas)
func_other(x)

5.0

In [ ]:
x1 = np.random.rand(50)
x1[np.random.randint(50, size = 10)] = 0
x2 = np.random.rand(1000)
x2[np.random.randint(1000, size = 100)] = 0
x3 = np.random.rand(10000)
x3[np.random.randint(10000, size = 10000)] = 0

In [ ]:
%timeit func_vectorize(x1)
%timeit func_not_vectorize(x1)
%timeit func_other(x1)

The slowest run took 9.64 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 5: 10.8 µs per loop
10000 loops, best of 5: 25.1 µs per loop
10000 loops, best of 5: 109 µs per loop


In [ ]:
%timeit func_vectorize(x2)
%timeit func_not_vectorize(x2)
%timeit func_other(x2)

The slowest run took 8.50 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 5: 10.1 µs per loop
1000 loops, best of 5: 443 µs per loop
1000 loops, best of 5: 1.16 ms per loop


In [ ]:
%timeit func_vectorize(x3)
%timeit func_not_vectorize(x3)
%timeit func_other(x3)

10000 loops, best of 5: 75.3 µs per loop
100 loops, best of 5: 5.46 ms per loop
10 loops, best of 5: 53.7 ms per loop


# Задание 5.
Дан трёхмерный массив, содержащий изображение, размера (height, width, numChannels), а также вектор длины numChannels. Сложить каналы изображения с указанными весами, и вернуть результат в виде матрицы размера (height, width). Считать реальное изображение можно при помощи функции scipy.misc.imread (если изображение не в формате png, установите пакет pillow: conda install pillow). Преобразуйте цветное изображение в оттенки серого, использовав коэффициенты np.array([0.299, 0.587, 0.114]).

In [ ]:
import numpy as np
import imageio
img1 = imageio.imread("test1.png")[:, :, :3] #410x489
img2 = imageio.imread("test2.png")[:, :, :3] #1024x670
img3 = imageio.imread("test3.png")[:, :, :3] #2000x1842
weights = np.array([0.299, 0.587, 0.114])

In [ ]:
def func_vectorize(img, weights):
    res = np.sum(img * weights, axis=2).astype(np.uint8)
    imageio.imsave("res.png", res)
    return res
func_vectorize(img1, weights)

array([[76, 76, 76, ..., 76, 76, 76],
       [76, 76, 76, ..., 76, 76, 76],
       [76, 76, 76, ..., 76, 76, 76],
       ...,
       [76, 76, 76, ..., 76, 76, 76],
       [76, 76, 76, ..., 76, 76, 76],
       [76, 76, 76, ..., 76, 76, 76]], dtype=uint8)

In [ ]:
def func_not_vectorize(img, weights):
    res = np.zeros(img[:, :, 1].shape).astype(np.uint8)
    for i in range(img.shape[0]):
        for j in range(img.shape[1]):
            res[i, j] = weights[0] * img[i, j, 0] + weights[1] * img[i, j, 1] + weights[2] * img[i, j, 2]
    imageio.imsave("res.png", res)
    return res[:, :]
func_not_vectorize(img1, weights)

array([[76, 76, 76, ..., 76, 76, 76],
       [76, 76, 76, ..., 76, 76, 76],
       [76, 76, 76, ..., 76, 76, 76],
       ...,
       [76, 76, 76, ..., 76, 76, 76],
       [76, 76, 76, ..., 76, 76, 76],
       [76, 76, 76, ..., 76, 76, 76]], dtype=uint8)

In [ ]:
def func_other(img, weights):
    res = (weights[0] * img[:, :, 0] + weights[1] * img[:, :, 1] + weights[2] * img[:, :, 2]).astype(np.uint8)
    imageio.imsave("res.png", res)
    return res
func_other(img1, weights)

Array([[76, 76, 76, ..., 76, 76, 76],
       [76, 76, 76, ..., 76, 76, 76],
       [76, 76, 76, ..., 76, 76, 76],
       ...,
       [76, 76, 76, ..., 76, 76, 76],
       [76, 76, 76, ..., 76, 76, 76],
       [76, 76, 76, ..., 76, 76, 76]], dtype=uint8)

In [ ]:
%timeit func_vectorize(img1, weights)
%timeit func_not_vectorize(img1, weights)
%timeit func_other(img1, weights)

10 loops, best of 5: 68 ms per loop
1 loop, best of 5: 458 ms per loop
10 loops, best of 5: 62.5 ms per loop


In [ ]:
%timeit func_vectorize(img2, weights)
%timeit func_not_vectorize(img2, weights)
%timeit func_other(img2, weights)

1 loop, best of 5: 242 ms per loop
1 loop, best of 5: 1.6 s per loop
1 loop, best of 5: 223 ms per loop


In [ ]:
%timeit func_vectorize(img3, weights)
%timeit func_not_vectorize(img3, weights)
%timeit func_other(img3, weights)

1 loop, best of 5: 1.85 s per loop
1 loop, best of 5: 9.06 s per loop
1 loop, best of 5: 1.76 s per loop


# Задача 6.
Реализовать кодирование длин серий (Run-length encoding). Дан вектор x. Необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.

In [ ]:
import numpy as np
x = np.array([2, 2, 2, 3, 3, 3, 5])

In [ ]:
def func_not_vectorize(x):
    numbers = np.array([])
    repeat = np.array([])
    for i in x:
        if len(numbers) == 0 or i != numbers[len(numbers)-1]:
            numbers = np.append(numbers, i)
            repeat = np.append(repeat, 1)
        else:
            repeat[len(repeat)-1] = repeat[len(repeat)-1] + 1
    return (numbers, repeat)
func_not_vectorize(x)

(array([2., 3., 5.]), array([3., 3., 1.]))

In [ ]:
def func_vectorize(x):
    positions = np.append(np.array(0), np.where(np.diff(x) != 0)[0] + 1)
    numbers = x[positions]
    repeat = np.diff(np.append(positions, len(x)))
    return (numbers, repeat)
func_vectorize(x)

(array([2, 3, 5]), array([3, 3, 1]))

In [ ]:
def func_other(x):
    positions = np.array([0])
    for i in range(1, len(x)):
        if x[i] != x[i-1]:
            positions = np.append(positions, i)
    numbers = x[positions]
    repeat = np.array([])
    for i in range(1, len(positions)):
        repeat = np.append(repeat, positions[i]-positions[i-1])
    repeat = np.append(repeat, len(x)-positions[i])
    return (numbers, repeat)
func_other(x)

(array([2, 3, 5]), array([3., 3., 1.]))

In [ ]:
x1 = np.random.randint(10, size = 50)
x2 = np.random.randint(10, size = 1000)
x3 = np.random.randint(10, size = 10000)

In [ ]:
%timeit func_vectorize(x1)
%timeit func_not_vectorize(x1)
%timeit func_other(x1)

The slowest run took 66.94 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 5: 27.8 µs per loop
1000 loops, best of 5: 748 µs per loop
1000 loops, best of 5: 614 µs per loop


In [ ]:
%timeit func_vectorize(x2)
%timeit func_not_vectorize(x2)
%timeit func_other(x2)

The slowest run took 5.11 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 5: 33 µs per loop
100 loops, best of 5: 15.4 ms per loop
100 loops, best of 5: 12.9 ms per loop


In [ ]:
%timeit func_vectorize(x3)
%timeit func_not_vectorize(x3)
%timeit func_other(x3)

The slowest run took 8.12 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 5: 82.7 µs per loop
10 loops, best of 5: 168 ms per loop
10 loops, best of 5: 144 ms per loop


# Задание 7.
Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравнить с функцией scipy.spatial.distance.cdist.

In [ ]:
import numpy as np
import scipy.spatial.distance as ssd
x = np.array([[ 35.0456, -85.2672],
              [ 35.1174, -89.9711],
              [ 35.9728, -83.9422],
              [ 36.1667, -86.7833]])
y = x

In [ ]:
def func_not_vectorize(x, y):
    res = np.zeros((x.shape[0], y.shape[0]))
    for i in range(res.shape[0]):
        for j in range(res.shape[1]):
            for k in range(x.shape[1]):
                res[i, j] += (x[i, k] - y[j, k])**2
            res[i, j] = np.sqrt(res[i, j])
    return res
func_not_vectorize(x, y)

array([[0.        , 4.70444794, 1.6171966 , 1.88558331],
       [4.70444794, 0.        , 6.0892811 , 3.35605413],
       [1.6171966 , 6.0892811 , 0.        , 2.84770898],
       [1.88558331, 3.35605413, 2.84770898, 0.        ]])

In [ ]:
def func_vectorize(x, y):
    return ssd.cdist(x, y)
func_vectorize(x, y)

array([[0.        , 4.70444794, 1.6171966 , 1.88558331],
       [4.70444794, 0.        , 6.0892811 , 3.35605413],
       [1.6171966 , 6.0892811 , 0.        , 2.84770898],
       [1.88558331, 3.35605413, 2.84770898, 0.        ]])

In [ ]:
#(x[0]-y[0])**2 + (x[1]-y[1])**2 = x[0]**2 + y[0]**2 + x[1]**2 + y[1]**2 - 2*(x[0]*y[0] + x[1]*y[1])
def func_other(x, y):
    res = np.sqrt(np.add.outer(np.sum(x**2, axis=1), np.sum(y**2, axis=1)) - 2*np.dot(x, y.T))
    return res
func_other(x, y)

array([[0.        , 4.70444794, 1.6171966 , 1.88558331],
       [4.70444794, 0.        , 6.0892811 , 3.35605413],
       [1.6171966 , 6.0892811 , 0.        , 2.84770898],
       [1.88558331, 3.35605413, 2.84770898, 0.        ]])

In [ ]:
x1 = np.random.rand(10, 3)
y1 = np.random.rand(20, 3)
x2 = np.random.rand(100, 10)
y2 = np.random.rand(200, 10)
x3 = np.random.rand(200, 30)
y3 = np.random.rand(200, 30)

In [ ]:
%timeit func_vectorize(x1, y1)
%timeit func_not_vectorize(x1, y1)
%timeit func_other(x1, y1)

The slowest run took 6.92 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 5: 15.4 µs per loop
1000 loops, best of 5: 1.2 ms per loop
The slowest run took 140.48 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 5: 23.1 µs per loop


In [ ]:
%timeit func_vectorize(x2, y2)
%timeit func_not_vectorize(x2, y2)
%timeit func_other(x2, y2)

10000 loops, best of 5: 200 µs per loop
1 loop, best of 5: 295 ms per loop
10000 loops, best of 5: 125 µs per loop


In [ ]:
%timeit func_vectorize(x3, y3)
%timeit func_not_vectorize(x3, y3)
%timeit func_other(x3, y3)

1000 loops, best of 5: 863 µs per loop
1 loop, best of 5: 1.55 s per loop
1000 loops, best of 5: 553 µs per loop
